### ISSUE TITLE
eebo_adorned INPUT_FOLDER

### ISSUE THREAD

**Issue by dHannasch** [spenteco/faster_tcp_text_reuse#1]
Can you say where exactly you obtained the morphadorned EEBO-TCP TEI XML (not the XML the TCP ships, but XML derived from the TCP's SGML) that becomes the INPUT_FOLDER = '/home/spenteco/0/eebo_adorned/'?

**Comment by spenteco** [comment]
UMich seems to have moved the Box location of their TCP files, which is terrible.  And which makes the rest of my answer moot.

In any case, we've moved on to a new version of the corpus, all morphadorned, which is available here:  https://bitbucket.org/eplib/eebotcp/src/master/  The new version has slightly different markup, so you'll want to look at an example and compare it to the code where the XML is ingested.  The differences should be fairly obvious.

Please note that this repo was part of off-and-on work-in-progress, which has not been pushed to the point where it yields literary insight in the aggregate.  It can be interesting in the case of particular works, but isn't much use for more than that.

If I may ask, what interests you in the this repo?  If I knew a bit more about your interest, I might be able to be more helpful.
